# coding: utf-8

"""
    LOCKSS Configuration Service REST API

    API of the LOCKSS Configuration REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_configuration
from lockss_configuration.models.config_exchange import ConfigExchange  # noqa: E501
from lockss_configuration.rest import ApiException


class TestConfigExchange(unittest.TestCase):
    """ConfigExchange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigExchange(self):
        """Test ConfigExchange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lockss_configuration.models.config_exchange.ConfigExchange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
