# coding: utf-8

"""
    LOCKSS Configuration Service REST API

    API of the LOCKSS Configuration REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_configuration
from lockss_configuration.lockss-configuration-python.config_mod_spec import ConfigModSpec  # noqa: E501
from lockss_configuration.rest import ApiException


class TestConfigModSpec(unittest.TestCase):
    """ConfigModSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigModSpec(self):
        """Test ConfigModSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lockss_configuration.models.config_mod_spec.ConfigModSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
