# coding: utf-8

"""
    LOCKSS Configuration Service REST API

    API of the LOCKSS Configuration REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_configuration
from lockss_configuration.api.status_api import StatusApi  # noqa: E501
from lockss_configuration.rest import ApiException


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = lockss_configuration.api.status_api.StatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_status(self):
        """Test case for get_status

        Get the status of the service  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
