# coding: utf-8

"""
    LOCKSS Configuration Service REST API

    API of the LOCKSS Configuration REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_configuration
from lockss_configuration.api.config_api import ConfigApi  # noqa: E501
from lockss_configuration.rest import ApiException


class TestConfigApi(unittest.TestCase):
    """ConfigApi unit test stubs"""

    def setUp(self):
        self.api = lockss_configuration.api.config_api.ConfigApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_last_update_time(self):
        """Test case for get_last_update_time

        Get the timestamp when the configuration was last updated  # noqa: E501
        """
        pass

    def test_get_loaded_url_list(self):
        """Test case for get_loaded_url_list

        Get the URLs from which the configuration was loaded  # noqa: E501
        """
        pass

    def test_get_section_config(self):
        """Test case for get_section_config

        Get the named configuration file  # noqa: E501
        """
        pass

    def test_get_url_config(self):
        """Test case for get_url_config

        Get the configuration file for a URL  # noqa: E501
        """
        pass

    def test_put_config(self):
        """Test case for put_config

        Store the named configuration file  # noqa: E501
        """
        pass

    def test_put_config_reload(self):
        """Test case for put_config_reload

        Request a configuration reload  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
