# coding: utf-8

"""
    LOCKSS Configuration Service REST API

    API of the LOCKSS Configuration REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_configuration
from lockss_configuration.api.aus_api import AusApi  # noqa: E501
from lockss_configuration.rest import ApiException


class TestAusApi(unittest.TestCase):
    """AusApi unit test stubs"""

    def setUp(self):
        self.api = lockss_configuration.api.aus_api.AusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_au_config(self):
        """Test case for delete_au_config

        Delete the configuration of an AU  # noqa: E501
        """
        pass

    def test_get_all_au_config(self):
        """Test case for get_all_au_config

        Get the configurations of all AUs  # noqa: E501
        """
        pass

    def test_get_au_config(self):
        """Test case for get_au_config

        Get the configuration of an AU  # noqa: E501
        """
        pass

    def test_put_au_config(self):
        """Test case for put_au_config

        Store the configuration of an AU  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
